kind: pipeline
name: default

steps:
- name: tests
  image: python:3-slim
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
  commands:
  - apt-get update && apt-get install -y make git
  - pip install -r requirements.txt
  - make test-ci COMMIT_SHA=${DRONE_COMMIT_SHA}

- name: Build and send to Docker Hub
  image: plugins/docker
  settings:
    repo: gcavalcante8808/labels2env
    tags:
      - ${DRONE_COMMIT_SHA}
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

- name: release's binaries tests
  image: gcavalcante8808/labels2env:${DRONE_COMMIT_SHA}
  commands:
  - make build_and_test_release_binaries

- name: release
  image: gcavalcante8808/labels2env:${DRONE_COMMIT_SHA}
  environment:
    GITHUB_TOKEN:
      from_secret: GHR_TOKEN
  commands:
  - make release GITHUB_TOKEN=$${GITHUB_TOKEN}
  when:
    branch: master
